### ISSUE TITLE
next and back buttons are not working

### ISSUE THREAD

**Issue by coryrobbins** [coryrobbins/MailTag#2]
The next and back indexing is not working on the front-end

**Comment by jmetz** [comment]
I think the issue is that your form is malformed (no pun intended 😅):

https://github.com/coryrobbins/LabelBuddy/blob/29b5f531c1523af24e32b716b364872df9611d1d/templates/index.html#L68

So the action URL will always point to the same index!

**Comment by jmetz** [comment]
The fix is to make the "index" parameter be part of the post-data, not one of the get parameters. 

Unless you override the get parameters with post data?

**Comment by coryrobbins** [comment]
Ok, I will take a look and see - Thanks so much!

**Comment by jmetz** [comment]
I just checked - in this section you would need to override (ie reassign) `index`:

https://github.com/coryrobbins/LabelBuddy/blob/29b5f531c1523af24e32b716b364872df9611d1d/app.py#L68

**Comment by jmetz** [comment]
As it is at the moment, you only use `index` as it's set in the get parameters. 

Does this make sense?

**Comment by coryrobbins** [comment]
It does a bit, yes.

**Comment by jmetz** [comment]
(alternatively you could switch to _only_ using get parameters, if it's appropriate - which usually just means if the amount of data you need to pass back to the server is pretty small, and isn't sensitive data)

**Comment by coryrobbins** [comment]
Thanks so much, Jeremy!
